### ISSUE TITLE
plugin build fails

### ISSUE THREAD

**Issue by rajsameer** [vertica/vertica-grafana-datasource#2]
Hey guys,

Unable to build the plugin.
Following are my specs.
OS: Centos 7
node: v16.1.0
npm: 7.11.2
yarn v1.22.11
```text
yarn build    
yarn run v1.22.11   
$ grafana-toolkit plugin:build
  (node:23873) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./2020/" in the "exports" field module resolution of the package at /grafanaplugins/vertica-grafana-datasource/node_modules/es-abstract/package.json.
  Update this package.json to use a subpath pattern like "./2020/*".
  (Use `node --trace-deprecation ...` to show where the warning was created)
  Using Node.js [object Object]
  Using @grafana/toolkit [object Object]
✔ Preparing
⠋ Linting  (node:23873) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./helpers/" in the "exports" field module resolution of the package at /grafanaplugins/vertica-grafana-datasource/node_modules/es-abstract/package.json.
  Update this package.json to use a subpath pattern like "./helpers/*".
⠙ Linting  Trace: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser/tokenizers/description.js' is not defined by "exports" in /grafanaplugins/vertica-grafana-datasource/node_modules/@es-joy/jsdoccomment/node_modules/comment-parser/package.json
      at new NodeError (node:internal/errors:363:5)
      at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
      at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
      at resolveExports (node:internal/modules/cjs/loader:478:36)
      at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
      at Function.Module._load (node:internal/modules/cjs/loader:774:27)
      at Module.require (node:internal/modules/cjs/loader:1013:19)
      at require (node:internal/modules/cjs/helpers:93:18)
      at Object.<anonymous> (/grafanaplugins/vertica-grafana-datasource/node_modules/@es-joy/jsdoccomment/dist/index.cjs.cjs:7:28)
      at Module._compile (node:internal/modules/cjs/loader:1109:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
      at Module.load (node:internal/modules/cjs/loader:989:32)
      at Function.Module._load (node:internal/modules/cjs/loader:829:14)
      at Module.require (node:internal/modules/cjs/loader:1013:19)
      at require (node:internal/modules/cjs/helpers:93:18) {
    code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
  }
      at /grafanaplugins/vertica-grafana-datasource/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:25:29
      at step (/grafanaplugins/vertica-grafana-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:140:27)
      at Object.throw (/grafanaplugins/vertica-grafana-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:121:57)
      at rejected (/grafanaplugins/vertica-grafana-datasource/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:112:69)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
✖ Failed to load plugin 'jsdoc' declared in '--config » ./node_modules/@grafana/eslint-config/index.js': Package subpath './lib/parser/tokenizers/description.js' is not defined by "exports" in /grafanaplugins/vertica-grafana-datasource/node_modules/@es-joy/jsdoccomment/node_modules/comment-parser/package.json
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rajsameer** [comment]
yarn upgrade eslint-plugin-jsdoc@^35.0.0 fixed this issue.

**Comment by tanvipise** [comment]
I used the following commands to fix the issue:
- npm install @babel/helper-compilation-targets --save-dev
- npm audit fix
